apiVersion: v1
kind: Pod

metadata:
  name: debug
  namespace: default
  labels:
    env: study

spec:
  containers:
  - name: debug
    image: centos:7
    command:
    - "sh"
    - "-c"
    args:
    - |
      while true
      do
        sleep ${DELAY}
      done
    env: 
      - name: "DELAY"
        value: "$"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"


---
apiVersion: v1
kind: Pod

metadata:
  name: nginx
  namespace: default
  labels:
    env: study
  
spec:
  containers:
  - name: nginx
    image: nginx:1.17.2-alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"