apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: default
  labels:
    app: weblog
    env: study 
spec:
  containers:
  - name: debug
    image: debug
    imagePullPolicy: Never # ローカルDockerイメージを探す
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
    - "sh"
    - "-c"
    args:
    - |
      while true
      do
        sleep 5
      done